# Generated by Django 2.1 on 2020-01-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0003_auto_20200128_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_umpire_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_umpire_id', to='crt.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='man_of_the_match',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='man_of_the_match', to='crt.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_winner_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner_team', to='crt.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_umpire_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_umpire_id', to='crt.Player'),
        ),
    ]
