# Generated by Django 2.1 on 2020-01-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0006_auto_20200128_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='crt.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='crt.Team'),
        ),
    ]
