# Generated by Django 2.1 on 2020-01-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0007_auto_20200128_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crt.League'),
        ),
    ]
